---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html
- hosts: all
  vars:
    hostname: shasha
  tasks:
  - name: Kill Java Process related to XMS
    win_shell: Stop-Process -Name "java" -Force
    register: running_processes
    failed_when: running_processes.rc == -1
  - name: Kill NMX Validator Process related to XMS
    win_shell: Stop-Process -Name "NMXValidatorService" -Force
    register: running_processes
    failed_when: running_processes.rc == -1
  - name: Kill NMXNG Process related to XMS
    win_shell: Stop-Process -Name "NmxNgServerController" -Force
    register: running_processes
    failed_when: running_processes.rc == -1
