---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html
- hosts: all
  vars:
    hostname: shasha
  tasks:
    - name: Get running processes
      win_shell: Get-Process java
      register: running_processes
    - name: Kill Java Process
      win_shell: Stop-Process -Name "java" -Force
      when: running_processes.stat.exists == true