---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html
- hosts: all
  tasks:
    - name: Fetch a info file
      fetch: src=C:/DatabaseBkup/MetaData.xml dest=/home/user/MetaData.xml flat=yes 