---
- hosts: all
  vars:
    hostname: shasha
  tasks:
    - set_fact:
        catalogName: "{{catalog_url.split('/')[-1]}}"
    - name: Download catalog from specified URL
      win_get_url:
        url: "{{catalog_url}}"
        dest: c:\DatabaseBkup\
        url_username: "{{url_username}}"
        url_password: "{{url_password}}"
    - name: Copy the Catalog file to Temp
      win_copy:
        src: C:\DatabaseBkup\{{catalogName}}
        dest: C:\temp\{{catalogName}}
        remote_src: yes
    - name: Rename the catalog file
      win_command: cmd.exe /C rename C:\temp\{{catalogName}} TestAnsible1.zip
    - name: Unzip the catalog to get metadataxml
      win_unzip:
        src: C:\temp\TestAnsible1.zip
        dest: C:\temp\temp
        rm: True
    - name: Run shell command to read xml file and NMX version
      win_shell: |
        [xml]$xml = Get-Content C:\temp\temp\MetaData.xml
        $xml.DatabaseList.Item.Info.CreatedBy
      register: shell_result
    - set_fact:
        buildnumber: "{{shell_result.stdout_lines[0]}}"
    - debug:
        msg: Abc
      when: buildnumber.find("eng") == -1
    - set_fact:
        version: "trunk"
      when: buildnumber.find("eng") != -1
    - set_fact:
        constructbuildnumber: "{{buildnumber.split('.')}}"
      when: buildnumber.find("eng") == -1
    - set_fact:
        version: "{{constructbuildnumber[0]}}.{{constructbuildnumber[1]}}.x.{{constructbuildnumber[3]}}"
        buildnumber: "{{constructbuildnumber[0]}}.{{constructbuildnumber[1]}}.{{constructbuildnumber[2]}}.{{constructbuildnumber[3]}}.{{ constructbuildnumber[4] | regex_replace('^0', '')}}"
      when: constructbuildnumber[0] != -1
    - name: Delete the Unzipped folder
      win_file:
        path: C:\Temp\Temp
        state: absent
