---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html
- hosts: all
  vars:
    hostname: shasha
  tasks:
    - import_tasks: Test-Ansible-Commands.yml
      vars:
        hostname: abc
    - import_tasks: Test-Ansible-Commands.yml
      vars:
        hostname: shashank
    - name: Download ActivateCatalog zip
      win_get_url:
        url: "https://NMXAutomation@bitbucket360.harmonicinc.com/projects/NMXGROUP/repos/nmx_playbooks/browse/nmx_playbooks/ActivateCatalog.yml"
        dest: c:\temp\
    - name: run multi-lined shell commands
      win_shell: |
        [xml]$xml = Get-Content C:\DatabaseBkup\MetaData.xml
        $xml.DatabaseList.Item.Info.CreatedBy
      register: shell_result
    - debug:
        var: shell_result.stdout_lines[0]
     
#$xml.DatabaseList.Item.Info.CreatedBy	 
#    - name: Copy the Activate Catalog file
#      win_copy:
#        src: C:\DatabaseBkup\TestAnsible.hzp
#        dest: C:\temp\TestAnsible.hzp
#        remote_src: yes
#    - name: rename the file
#      win_command: cmd.exe /C rename C:\temp\TestAnsible.hzp TestAnsible1.zip
#    - name: Unzip the Download ActivateCatalog zip
#      win_unzip:
#        src: C:\DatabaseBkup\TestAnsible1.zip
#        dest: C:\temp\
#        rm: True