---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html
- hosts: all
  tasks:
    - name: Fetch a info file
      fetch: src=C:/DatabaseBkup/MetaData.xml dest=/home/user/MetaData.xml flat=yes 
    - name: Obtain information about a file
      win_stat:
        path: /home/user/MetaData.xml
      register: file_info
      win_xml:
        path: C:/DatabaseBkup/MetaData.xml
      register: file_info1
    - name: Read attribute value
      xml:
        path: C:/DatabaseBkup/MetaData.xml
        xpath: /DatabaseList
        content: attribute
        attribute: BackupAt
      register: xmlresp
    - name: Print the value
      debug:
        msg:{{xmlresp}}