---
- hosts: all
  vars:
    hostname: shasha
  tasks:
    - set_fact:
        catalogName: "{{catalog_url.split('/')[-1]}}"
    - import_tasks: ActivateCatalog.yml
      vars:
        catalogName: "{{catalogNameM}}"