---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html
- hosts: all
  vars:
    hostname: shasha
  tasks:
    - import_tasks: Test-Ansible-Commands.yml
      vars:
        hostname: abc
    - import_tasks: Test-Ansible-Commands.yml
      vars:
        hostname: shashank
    - name: Copy the Activate Catalog file
      win_copy:
        src: C:\DatabaseBkup\TestAnsible.hzp
        dest: C:\Temp\
        remote_src: yes
    - name: rename the file
      win_command: cmd.exe /C rename C:\Temp\TestAnsible.hzp TestAnsible1.zip
#    - name: Unzip the Download ActivateCatalog zip
#      win_unzip:
#        src: C:\DatabaseBkup\TestAnsible1.zip
#        dest: C:\temp\
#        rm: True