---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html
- hosts: all
  tasks:
    - name: Fetch a info file
      fetch: src=C:/DatabaseBkup/MetaData.xml dest=/tmp/ flat=yes 
    - name: Obtain information about a file
      win_stat:
        path: /tmp/MetaData.xml
      register: file_info
    - name: list files
      command: "ls /tmp/"
      register: dir_out
    - debug: msg="the value of MetaData.txt is {{lookup('file', '/tmp/MetaData.xml') }}"
    - name: Read attribute value
      xml:
        path: /tmp/MetaData.xml
        xpath: /DatabaseList
        content: attribute
        attribute: BackupAt
      register: xmlresp
#    - name: Print the value
#      debug:
#        msg:{{xmlresp}}