---
- hosts: all
  vars:
    hostname: shasha
  tasks:
    - set_fact:
        catalogNameM: "{{catalog_url.split('/')[-1]}}"
    - import_playbook: ActivateCatalog.yml catalogName = "{{catalogNameM}}"
    - include: ActivateCatalog.yml catalogName = "{{catalogNameM}}"
      remote_src: true