---
- hosts: all
  vars:
    hostname: shasha
  tasks:
    - name: Save the result of 'whoami' in 'whoami_out'
      win_command: AnsibleActivateCatalog.exe abc.hzp {{sql_servername}} {{sql_password}} {{ansible_host}}
      args:
        chdir: C:\Program Files\Harmonic\NMX\DOTNETGUI\
      register: whoami_out
#    - set_fact:
#        catalogNameM: "{{catalog_url.split('/')[-1]}}"
#    - import_playbook: ActivateCatalog.yml catalogName = "{{catalogNameM}}"
#    - include: ActivateCatalog.yml catalogName = "{{catalogNameM}}"
#      remote_src: true\	  
#when: shell_result.stdout_lines[0].find("eng") == -1
#    - set_fact:
#        constructbuildnumber: "{{shell_result.stdout_lines[0].split('.')}}"
#        version: "{{constructbuildnumber[0]}}.{{constructbuildnumber[1]}}.x.{{constructbuildnumber[3]}}"
#        buildnumber: "{constructbuildnumber[0]}}.{{constructbuildnumber[1]}}.{{constructbuildnumber[2]}}.{{constructbuildnumber[3]}}.{{constructbuildnumber[4]}}{{ constructbuildnumber[5] | regex_replace('^0/', '') }}"
#      when: shell_result.stdout_lines[0].find("eng") == -1		
#    - import_tasks: Test-Ansible-Commands.yml
#      vars:
#        hostname: abc
#    - import_tasks: Test-Ansible-Commands.yml
#      vars:
#        hostname: shashank
#    - name: Download ActivateCatalog zip
#      win_get_url:
#        url: "https://NMXAutomation@bitbucket360.harmonicinc.com/projects/NMXGROUP/repos/nmx_playbooks/browse/nmx_playbooks/Install_Uninstall_NMX.yml"
#        dest: c:\temp\  
#$xml.DatabaseList.Item.Info.CreatedBy	 
#    - name: Copy the Activate Catalog file
#      win_copy:
#        src: C:\DatabaseBkup\TestAnsible.hzp
#        dest: C:\temp\TestAnsible.hzp
#        remote_src: yes
#    - name: rename the file
#      win_command: cmd.exe /C rename C:\temp\TestAnsible.hzp TestAnsible1.zip
#    - name: Unzip the Download ActivateCatalog zip
#      win_unzip:
#        src: C:\DatabaseBkup\TestAnsible1.zip
#        dest: C:\temp\
#        rm: True