---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html
- hosts: all
  tasks:
    - name: Fetch a info file
      fetch: src=C:/DatabaseBkup/MetaData.xml dest=/var/lib/awx/projects/_29__test_ansible_windows/ flat=yes 
    - name: Obtain information about a file
      win_stat:
        path: /tmp/MetaData.xml
      register: file_info
    - debug: 
        msg1:"{{lookup('file', '/var/lib/awx/projects/_29__test_ansible_windows/MetaData.xml') }}"
    - name: Read attribute value
      xml:
        xmlstring: '{{msg1}}'
        xpath: /DatabaseList
        content: text
      register: xmlresp
    - name: Print the value
      debug:
        msg:{{xmlresp}}